### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by poulerik-dk** [thibautd/JSerial#1]
Seems to me that JNA is giving off this exception when trying to access the Jserial dll. Could you please guide me in the right direction on how to solve this? :) Running as administrator does not solve the issue.

```
dk.thibaut.serial.SerialException: Access is denied.

at dk.thibaut.serial.SerialPortWindows.getLastException(SerialPortWindows.java:92)
at dk.thibaut.serial.SerialPortWindows.<init>(SerialPortWindows.java:99)
at dk.thibaut.serial.SerialPort.open(SerialPort.java:75)
at SerialConnection.<init>(SerialConnection.java:32)
```

**Comment by thibautd** [comment]
Hello,

This error is returned by windows (it's the result of `CreateFile()` Win32 API function). Usually it means that the COM port is used by an other application. Is it the case ?

**Comment by poulerik-dk** [comment]
Tried rebooting to make sure, doesn't seem to be the case unfortunately. I am using a Prolific USB-to-Serial Comm Port, running on Windows 10... Using some very old drivers which seems to work (2008) (Tested with some wierd solution found on the internet, seems to work fine). 

Maybe my setup is at fault here.

**Comment by thibautd** [comment]
If you try with an other software like putty or termite, does it work ?

**Comment by poulerik-dk** [comment]
I just realised that you where indeed correct before - I am using the port twice. I am shortcircuiting pin 2 and 3 in order to test communication on the same com port.

Tried not opening both a read and a write and the program launched without any issues at all.

Im sorry for wasting your time :)

**Comment by thibautd** [comment]
No problem ! I think you are the first user of JSerial, so I'm glad to see that you're interested in the project, enjoy :-)
