### ISSUE TITLE
How to set timeOut() to non-blocking?

### ISSUE THREAD

**Issue by Jodes81** [thibautd/JSerial#3]
The documentation says it's possible to:

- Configure read timeout (milliseconds, infinite or non-blocking)

But I couldn't work out from the source code how to do that? I hit a dead ends looking at the abstract class that defines setTimeout().

Thanks

**Comment by thibautd** [comment]
The answer to your question is in the Javadoc:

http://thibautd.github.io/JSerial/dk/thibaut/serial/SerialPort.html#setTimeout-int-

Thanks for using JSerial :-)

**Comment by Jodes81** [comment]
Thanks for making it! I looked for something like this for years.
